import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Daniel",
      email: "danielkabagambe@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "janenakisales@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Men's Sports Shoes",
      slug: "Men's-Sports-Shoes",
      category: "Fashion sneaker's",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/44/700242/1.jpg?3344",
      price: 25000,
      countInStock: 5,
      brand: "Shoes",
      rating: 1.5,
      numReviews: 6,
      description: "Men's Sports Shoes-blue",
    },
    {
      // _id: "2",
      name: "Rosefoam Mattress",
      slug: "Rosefoam-Mattress",
      category: "Mattress",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/15/451799/1.jpg?5796",
      price: 39900,
      countInStock: 8,
      brand: "Rosefoam",
      rating: 1.7,
      numReviews: 8,
      description: "Rosefoam 5*12 Bonluxe Mattress",
    },
    {
      // _id: "3",
      name: "Hp Laptop silver",
      slug: "Hp-laptop-silver",
      category: "Laptop",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/92/2684801/1.jpg?2508",
      price: 1620000,
      countInStock: 8,
      brand: "Hp",
      rating: 1.9,
      numReviews: 9,
      description: "Rosefoam 5*12 Bonluxe Mattress",
    },
    {
      // _id: "4",
      name: "Hisense Tv",
      slug: "hisense-tv",
      category: "Tv",
      image:
        "https://ug.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/23/408248/1.jpg?3335",
      price: 750000,
      countInStock: 10,
      brand: "Tv",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Tv",
    },
    {
      // _id: "5",
      name: "Mosquito Net Cream",
      slug: "Mosquito-Net-Cream",
      category: "mosquito net",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/65/284482/1.jpg?2815",
      price: 37500,
      countInStock: 16,
      brand: "Mosquito Net ",
      rating: 4.5,
      numReviews: 10,
      description: "Pole Mosquito Net Cream",
    },
    {
      // _id: "6",
      name: "Hisense 6 Kg Washing Machine",
      slug: "Washing-Machine",
      category: "Appliances",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/34/096215/1.jpg?3524",
      price: 915000,
      countInStock: 18,
      brand: "Hisense",
      rating: 4.1,
      numReviews: 12,
      description: "easy to was clothes",
    },
    {
      // _id: "7",
      name: "Apple iPhone 15 Pro Max",
      slug: "Apple-iPhone-15-Pro-Max",
      category: "Apple Phones & Tablets",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/48/0072701/1.jpg?1033",
      price: 6150000,
      countInStock: 20,
      brand: "Apple",
      rating: 7.5,
      numReviews: 16,
      description: "Latest iphone",
    },
    {
      // _id: "8",
      name: "Kinyara Sweet Sugar",
      slug: "Kinyara-Sweet-Sugar",
      category: "Supermarket",
      image:
        "https://ug.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/41/03674/1.jpg?2381",
      price: 5400,
      countInStock: 13,
      brand: "kinyara sugar",
      rating: 4.5,
      numReviews: 19,
      description: "Kinyara Irresistibly Sweet Sugar",
    },
    {
      // _id: "9",
      name: "Door Window Curtains",
      slug: "Door-window-curtains",
      category: "Draperies and curtains",
      image:
        "https://ug.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/185758/1.jpg?7480",
      price: 84900,
      countInStock: 15,
      brand: "Curtains",
      rating: 3.5,
      numReviews: 11,
      description: "Suitable for doors",
    },
  ],
};
export default data;
